baseURL = 'https://wichaksono.github.io/'
languageCode = 'en-us'
title = 'Wichaksono | Hugo Site'
theme = "keepit"

# default amount of posts in each pages
paginate = 12
# google analytics code [UA-XXXXXXXX-X]
googleAnalytics = ""
# copyright description used only for seo schema
copyright = ""

# Header title config
[params.header.title]
    # URL of the LOGO
    logo = ""
    # title name
    name = "KeepIt"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = "<i class='far fa-kiss-wink-heart fa-fw' aria-hidden='true'></i>"
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # whether to use typeit animation for title name
    typeit = true

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Blog"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""

# Home page config
  [params.home]
    # amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/neon-icon-color.png"
      # title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page
      subtitle = "A Clean, Elegant but Advanced Hugo Theme"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = false
      # special amount of posts in each home posts page
      paginate = 6
    
    # Social config in home page
  [params.social]
    GitHub = "#"
    Facebook = "#"
    Telegram = "#"
    Whatsapp = "#"