baseURL = "https://wichaksono.github.io/"
languageCode = "en-us"
title = "Wichaksono W"
ignoreLogs = ["warning-goldmark-raw-html"]

[pagination]
  pagerSize = 6

[taxonomies]
  tag = "tags"
  project_tag = "projects/tags"

[params]
  description = "Fast, secure websites built with Hugo + Bootstrap"
  og_image = "/images/og-default.jpg"
  home_url = "#"
  project_url = "#"
  blog_url = "#"
  contact_url = "#"

[params.profile]
  name = "Wakhid Wichaksono"
  title = "WordPress Development"
  quote = ""
  photo = "https://placehold.co/120x120/1f2937/ffffff?text=DEV"

# ======================
#  Link Utama (Tombol)
# ======================

[[params.links]]
  icon = "facebook"
  text = "Facebook"
  url = "https://www.facebook.com/groups/2368671900122872"
  newtab = true

[[params.links]]
  icon = "youtube"
  text = "YouTube"
  url = "https://youtube.com/@username"
  newtab = true

[[params.links]]
  icon = "message-circle-code"
  text = "WhatsApp"
  url = "https://wa.me/6282244274544"
  newtab = true

[[params.links]]
  icon = "badge-info"
  text = "About me"
  url = "/about"
  newtab = false


# ======================
#  FLOATING NAVIGATION
# ======================
[params.floatingnav]
  enabled = true
  active = "contact" # bisa: home, portfolio, blog, contact

[[params.floatingnav.items]]
  icon = "hammer"
  label = "Services"
  url = "/services"
  id = "services"

[[params.floatingnav.items]]
  icon = "monitor"
  label = "Portfolio"
  url = "/projects"
  id = "portfolio"

[[params.floatingnav.items]]
  icon = "pencil"
  label = "Blog"
  url = "/blog"
  id = "blog"

[[params.floatingnav.items]]
  icon = "message-square-code"
  label = "Contact"
  url = "/"
  id = "contact"