baseURL = 'https://wichaksono.github.io/'
languageCode = 'en-us'
title = 'Wichaksono'
theme = "keepit"

# default amount of posts in each pages
paginate = 12
# google analytics code [UA-XXXXXXXX-X]
googleAnalytics = ""
# copyright description used only for seo schema
copyright = ""

# Header title config
[params.header.title]
    # URL of the LOGO
    logo = ""
    # title name
    name = "Wichaksono"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = "<i class='fa-solid fa-terminal'></i>"
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # whether to use typeit animation for title name
    typeit = true

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = ""
    pre = "<i class='fa-brands fa-github'></i>"
    post = ""
    name = "My Repository"
    url = "https://github.com/wichaksono"
    title = "My Repository"
  [[menu.main]]
    weight = 2
    identifier = "about"
    pre = "<i class='fa-solid fa-address-card'></i>"
    post = ""
    name = "About"
    url = "/about"
    title = "About"
 [[menu.main]]
    weight = 3
    identifier = "posts"
    pre = "<i class='fa-solid fa-book'></i>"
    post = ""
    name = "Blog"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  

# Home page config
  [params.home]
    # amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/neon-icon-color.png"
      # title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page
      subtitle = "A Clean, Elegant but Advanced Hugo Theme"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = false
      # special amount of posts in each home posts page
      paginate = 6
    
    # Social config in home page
  [params.social]
    GitHub = "#"
    Facebook = "#"
    Telegram = "#"
    Whatsapp = "#"

# Footer config
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    custom = ""
    # whether to show Hugo and theme info
    hugo = false
    # whether to show copyright info
    copyright = true
    # whether to show the author
    author = true
    # site creation time
    since = 2022
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license= ""